### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/train_x.txt'

### ISSUE THREAD

**Issue by robotzheng** [toru34/zhou_acl_2017#1]
[root@A01-R04-I220-11 zhou_acl_2017]# python3 train.py --n_epochs 10 --batch_size 32 --emb_dim 64 --hid_dim 64 --vocab_size 30000 --maxout_dim 10
[dynet] random seed: 42
[dynet] using autobatching
[dynet] allocating memory: 1024MB
[dynet] memory allocation done.
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    main()
  File "train.py", line 43, in main
    w2c = build_word2count('./data/train_x.txt')
  File "/home/zzt/zhou_acl_2017/utils.py", line 8, in build_word2count
    for line in open(file_path, encoding='utf-8'):
FileNotFoundError: [Errno 2] No such file or directory: './data/train_x.txt'

thanks

**Comment by toru34** [comment]
sorry

I've fixed it. It probably works now.
