### ISSUE TITLE
ImportError: No module named '_gdynet'

### ISSUE THREAD

**Issue by robotzheng** [toru34/zhou_acl_2017#3]
[root@A01-R04-I220-11 zhou_acl_2017]# python3 train.py --n_epochs 20 --gpu 0
Traceback (most recent call last):
  File "train.py", line 177, in <module>
    main()
  File "train.py", line 35, in main
    import _gdynet as dy # Use gpu
ImportError: No module named '_gdynet'

**Comment by toru34** [comment]
Thank you.

Please set `--gpu -1` for cpu. I've fixed readme.

**Comment by robotzheng** [comment]
[root@A01-R04-I220-11 zhou_acl_2017]# python3 train.py --n_epochs 20 --gpu -1
[dynet] initializing CUDA
CUDA failure in cudaGetDeviceCount(&nDevices)
no CUDA-capable device is detected
terminate called after throwing an instance of 'dynet::cuda_exception'
  what():  cudaGetDeviceCount(&nDevices)
Aborted (core dumped)

**Comment by robotzheng** [comment]
Unify gdynet and dynet use in DyNet #781

gdynet has been dispeared in 2.01

**Comment by robotzheng** [comment]
Unify gdynet and dynet use in DyNet #781

gdynet has been disappeared in 2.01

**Comment by toru34** [comment]
ok. thanks

**Comment by toru34** [comment]
fixed. thank you
